# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install

      - name: install global blitz
        run: npm i -g blitz

      # Runs a single command using the runners shell
      - name: build project
        run: blitz build
        env:
          NEXT_PUBLIC_BACKGROUND_URL: https://js-talks.builtforfifty.workers.dev//bg2.jpg
          NEXT_PUBLIC_FORM_EMBED_IFRAME: "<iframe class='airtable-embed' src='https://airtable.com/embed/shrnVkMKyRztuJ3qq?backgroundColor=cyan' frameborder='0' onmousewheel='' width='100%' height='533' style='background: transparent; border: 1px solid #ccc;height: 2350px;'></iframe>"
          SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}

      - name: rsync blitz folder
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: .blitz/
          remote_path: /home/abuuzayr/techjobs/
          remote_host: 128.199.136.148
          remote_user: abuuzayr
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: rsync next folder
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: .next/
          remote_path: /home/abuuzayr/techjobs/
          remote_host: 128.199.136.148
          remote_user: abuuzayr
          remote_key: ${{ secrets.DEPLOY_KEY }}
